pipeline {
    agent any
    stages {
        stage('checkout') {
            steps {
                git 'https://github.com/abdoelwaly/jenkins.git'
            }
        }
        stage('ci') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'lappass', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                    sh """
                    docker build . -f dockerfile -t abdooelwaly/learningimages
                    echo \$PASSWORD | docker login -u \$USERNAME --password-stdin
                    docker push abdooelwaly/learningimages
                    """
                }
            }
        }
        stage('cd') {
            steps {
                sh """
                docker run -d -p 3000:3000 --name jenkinslab abdooelwaly/learningimages
                """
            }
        }
    }
    post {
        cleanup {
            cleanWs()
        }
    }
}